version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/matzehuels/stacktower

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - misspell
    - unconvert

  settings:
    staticcheck:
      checks:
        - all
        - -ST1000  # package comments
        - -ST1016  # receiver names
        - -QF1003  # tagged switch suggestion
