# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  # CLI binary (stacktower) - for end users
  - id: stacktower
    main: ./cmd/stacktower
    binary: stacktower
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/matzehuels/stacktower/pkg/buildinfo.Version={{.Version}}
      - -X github.com/matzehuels/stacktower/pkg/buildinfo.Commit={{.Commit}}
      - -X github.com/matzehuels/stacktower/pkg/buildinfo.Date={{.Date}}

archives:
  # CLI archive (for Homebrew, manual download)
  - id: stacktower
    builds:
      - stacktower
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "README"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: matzehuels
    name: stacktower
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Stacktower {{.Version}}

    A tool for visualizing dependency graphs as elegant "stack tower" diagrams.

    ### Installation

    Download the appropriate binary for your platform below, or install via Go:

    ```bash
    go install github.com/matzehuels/stacktower@{{.Tag}}
    ```

  footer: |
    **Full Changelog**: https://github.com/matzehuels/stacktower/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: stacktower
    repository:
      owner: matzehuels
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/matzehuels/stacktower
    description: Visualize dependency graphs as elegant stacked tower diagrams
    license: Apache-2.0
    test: |
      system "#{bin}/stacktower", "--version"
    install: |
      bin.install "stacktower"
