name: Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
      placeholder: A clear description of the feature
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this? What problem does it solve?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternatives?
    validations:
      required: false

